[package]
name = "hellorust"
version = "0.1.0"
authors = ["Troy Martin <beef.erikson.studios@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.7.0"}